name = "JuDO"
uuid = "3ecbce6f-598f-4154-83ab-9a3a807c6d0a"
authors = ["Haochen Tao <54142141+shawn-tao01@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
